const BASE_URL = "SLN_UrlBackEndServer";
const STORAGE_KEY_AUTH = 'SLN_AuthToken';
const STORAGE_KEY_BUILDING = 'buildingData';
const STORAGE_KEY_FLOOR = 'floorData';
const STORAGE_KEY_LOCATION = 'locationData';


export {BASE_URL, STORAGE_KEY_AUTH, STORAGE_KEY_BUILDING, STORAGE_KEY_FLOOR, STORAGE_KEY_LOCATION}